android_binary(
    name = "app",
    manifest = "AndroidManifest.xml",
    deps = ["//src/main/java/com/example/bazel:greeter_activity", "@maven//:com_google_android_material_material",

                                                                             "@maven//:androidx_appcompat_appcompat"
                                                                             ],

)
# "@maven//:androidx_appcompat_appcompat",
#                                                        "@maven//:androidx_core_core",